# Generated by Django 4.2.4 on 2025-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='low_quality_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/low_quality/'),
        ),
    ]
